### ISSUE TITLE
Тут сразу две проблемы, на самом деле...

### ISSUE THREAD

**Issue by evilunyuu** [inqus637/zachet_po_c#1]
https://github.com/inqus637/zachet_po_c/blob/125008d4f03c986a43a8a5815176303cb8936eee/main.cpp#L17-L20

Проблема первая: а что если в файле больше 99 строк?
Проблема вторая, связанная с первой: а нужно ли вообще вычитывать в память весь файл сразу? Не лучше ли будет это делать по одной строке за раз, пока файл не кончится?

**Comment by inqus637** [comment]
Пофиксил
